### ISSUE TITLE
Flarum 0.1.0-beta.11.1 无法正常使用

### ISSUE THREAD

**Issue by Arasple** [Csineneo/lang-simplified-chinese#8]
环境

> Flarum
> 0.1.0-beta.11.1
> PHP
> 7.3.13
> MySQL
> 10.1.41-MariaDB-0+deb9u1

安装中文拓展后，选择该语言，刷新后 Flarum 页面无法加载，显示
（繁/简 中文均是这种情况）

> An error occurred while trying to load this page.

**Comment by Csineneo** [comment]
已修正，請更新。

**Comment by Arasple** [comment]
感谢您！
